### ISSUE TITLE
Still working on this project?

### ISSUE THREAD

**Issue by tom71** [pklaus/smrt#1]
Hello,
I have an  TL-SG108PE and I tried your software. But I got an error:

```
smrt.cli --ip-address 192.168.0.38 --username admin --password admin  --loglevel debug --host-mac e0:d5:5e:1f:87:9c --switch-mac  50:C7:BF:EC:7D:8C query_port_mirror
DEBUG:smrt.network:Sending Header:  {'checksum': 0, 'sequence_id': 14, 'version': 1, 'error_code': 0, 'flag': 0, 'fragment_offset': 0, 'host_mac': b'\xe0\xd5^\x1f\x87\x9c', 'token_id': 0, 'check_length': 0, 'switch_mac': b'P\xc7\xbf\xec}\x8c', 'op_code': 1}
DEBUG:smrt.network:Sending Payload: {2305: b''}
DEBUG:smrt.network:Received Header:  {'checksum': 0, 'version': 1, 'host_mac': b'\xe0\xd5^\x1f\x87\x9c', 'switch_mac': b'P\xc7\xbf\xec}\x8c', 'op_code': 2, 'check_length': 36, 'error_code': 0, 'sequence_id': 14, 'fragment_offset': 0, 'flag': 0, 'token_id': 1484}
DEBUG:smrt.network:Received Payload: OrderedDict()
no response
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/smrt/network.py", line 79, in receive
    total_payload += payload
TypeError: can't concat bytes to collections.OrderedDict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.local/bin/smrt.cli", line 11, in <module>
    load_entry_point('smrt==0.1.dev0', 'console_scripts', 'smrt.cli')()
  File "/usr/local/lib/python3.5/dist-packages/smrt/smrt.py", line 36, in main
    sc.login(args.username, args.password)
  File "/usr/local/lib/python3.5/dist-packages/smrt/network.py", line 94, in login
    self.query(GET, get_token_id_payload())
  File "/usr/local/lib/python3.5/dist-packages/smrt/network.py", line 88, in query
    header, payload = self.receive()
  File "/usr/local/lib/python3.5/dist-packages/smrt/network.py", line 83, in receive
    raise ConnectionProblem()
NameError: name 'ConnectionProblem' is not defined
```

`tom@fhem:~/smrt/smrt$ sudo smrt.discovery
WARNING:smrt.discovery:('enp3s0', '192.168.0.38', 'e0:d5:5e:1f:87:9c', '192.168.0.255')
Found a switch:  Host:   (Interface: enp3s0   IP: 192.168.0.38  Broadcast: 192.168.0.255)
                 Switch: (Kind: TL-SG108PE    MAC Address: 50:C7:BF:EC:7D:8C   IP Address: 192.168.0.238)`

Did you have a hint for me? 
And how can I implement more actions?

My python version is: Python 3.5.3

Thank you
Thomas

**Comment by philippechataignon** [comment]
See my PR #2 which can resolve your problem.
